// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getLoanProviderByIDStmt, err = db.PrepareContext(ctx, getLoanProviderByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetLoanProviderByID: %w", err)
	}
	if q.getLoanProviderBySlugStmt, err = db.PrepareContext(ctx, getLoanProviderBySlug); err != nil {
		return nil, fmt.Errorf("error preparing query GetLoanProviderBySlug: %w", err)
	}
	if q.getLoanProvidersStmt, err = db.PrepareContext(ctx, getLoanProviders); err != nil {
		return nil, fmt.Errorf("error preparing query GetLoanProviders: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getLoanProviderByIDStmt != nil {
		if cerr := q.getLoanProviderByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLoanProviderByIDStmt: %w", cerr)
		}
	}
	if q.getLoanProviderBySlugStmt != nil {
		if cerr := q.getLoanProviderBySlugStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLoanProviderBySlugStmt: %w", cerr)
		}
	}
	if q.getLoanProvidersStmt != nil {
		if cerr := q.getLoanProvidersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLoanProvidersStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                        DBTX
	tx                        *sql.Tx
	getLoanProviderByIDStmt   *sql.Stmt
	getLoanProviderBySlugStmt *sql.Stmt
	getLoanProvidersStmt      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                        tx,
		tx:                        tx,
		getLoanProviderByIDStmt:   q.getLoanProviderByIDStmt,
		getLoanProviderBySlugStmt: q.getLoanProviderBySlugStmt,
		getLoanProvidersStmt:      q.getLoanProvidersStmt,
	}
}
