// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/tabbed/pqtype"
)

type LoanProvider struct {
	ProviderID                    string                `json:"provider_id"`
	Provider                      string                `json:"provider"`
	ProviderType                  string                `json:"provider_type"`
	ProviderAccountID             string                `json:"provider_account_id"`
	PreExpirationTokenRefreshMins int32                 `json:"pre_expiration_token_refresh_mins"`
	ProviderName                  string                `json:"provider_name"`
	ApiKey                        string                `json:"api_key"`
	ApiSecret                     string                `json:"api_secret"`
	ApiEnvironment                string                `json:"api_environment"`
	ApiBaseUrl                    string                `json:"api_base_url"`
	Labels                        json.RawMessage       `json:"labels"`
	CreateTime                    time.Time             `json:"create_time"`
	UpdateTime                    time.Time             `json:"update_time"`
	ProviderConfig                pqtype.NullRawMessage `json:"provider_config"`
}

type LspToken struct {
	ProviderID     sql.NullString `json:"provider_id"`
	AuthToken      sql.NullString `json:"auth_token"`
	ExpirationTime sql.NullTime   `json:"expiration_time"`
	CreateTime     sql.NullTime   `json:"create_time"`
	UpdateTime     sql.NullTime   `json:"update_time"`
}
