// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	GetLoanProviderByID(ctx context.Context, providerID string) (LoanProvider, error)
	GetLoanProviderBySlug(ctx context.Context, provider string) (LoanProvider, error)
	GetLoanProviders(ctx context.Context) ([]LoanProvider, error)
}

var _ Querier = (*Queries)(nil)
